import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/Banner'
import LpSection2 from '../components/LPsection2'
import LpSection3 from '../components/LPsection3'
import LpSection4 from '../components/LPsection4'
import LpSection5 from '../components/LPsection5'
import styles from '../styles/Home.module.css'
import "@fontsource/roboto";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Banner/>
     <LpSection2/>
      <LpSection3 />
      <LpSection4 />
      <LpSection5/>
      <footer className={styles.footer}>
       
      </footer>
    </div>
  )
}
